# -*- coding: utf-8 -*-
"""NumDL.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lbg7lGA9Uw_7iEfXTe_NPRpknYKw0Bo
"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim import Adam
import torchvision
import torchvision.transforms.v2 as transforms
import matplotlib.pyplot as plt
from PIL import Image
import os

# بنشوف إذا فيه كرت شاشة NVIDIA شغال عشان الكود يطير، وإذا ما فيه بنشغل الـ CPU العادي
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device running now: {device}")

# بنزل الداتا الجاهزة (60 ألف صورة للتعليم و 10 آلاف للاختبار) وبنحولها لتينسورس (مصفوفات رقمية)
train_set = torchvision.datasets.MNIST(
    root="./data/", train=True, download=True, transform=transforms.ToTensor()
)
valid_set = torchvision.datasets.MNIST(
    root="./data/", train=False, download=True, transform=transforms.ToTensor()
)

# الموزع الذكي بيقسم الـ 60 ألف صورة لمجموعات صغيرة، كل مرة 32 صورة عشان الكمبيوتر ما يعلق
batch_size = 32
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
valid_loader = DataLoader(valid_set, batch_size=batch_size, shuffle=False)

# هنا بنبني الغرف والممرات اللي بتمشي فيها الصورة عشان الذكاء الاصطناعي يفهمها
model = nn.Sequential(
    nn.Flatten(),                  # بيفرد الصورة المربعة (28x28) ويخليها سلك مستقيم طوله 784 بكسل
    nn.Linear(784, 512),           # غرفة الاستقبال: بتستقبل الـ 784 بكسل وبتشغل 512 عصبون
    nn.ReLU(),                     # دالة الذكاء: بتلغي السوالب وتساعد الشبكة تفهم الخطوط الملتوية والانحناءات
    nn.Linear(512, 512),           # الغرفة الوسطى: بتزيد السعة الاستيعابية عشان العقل يصير أذكى
    nn.ReLU(),                     # دالة ذكاء ثانية لزيادة الفهم
    nn.Linear(512, 10)             # غرفة المخرجات: 10 عصبونات، كل عصبون بيمثل رقم من 0 لـ 9
)
model.to(device)

# دالة مساعدة لحساب الدقة البشرية اللي بنفهمها
def get_batch_accuracy(output, y, N):
    pred = output.argmax(dim=1, keepdim=True)
    correct = pred.eq(y.view_as(pred)).sum().item()
    return correct / N

# الأستاذ اللي بصلح وبحسب كمية الغلط في التخمين والمصحح الذكي اللي بعدل الأرقام الداخلية للشبكة
loss_function = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters())

# هنا بنبلش مرحلة التدريب ونمر على الصور جولة ورا جولة
print("\n--- Starting AI Model Training ---")
epochs = 3  # كم مرة العقل الاصطناعي راح يقرأ كتاب الصور كامل (3 جولات ممتازة جداً)
train_N = len(train_loader.dataset)

for epoch in range(epochs):
    model.train() # بنشغل وضع التدريب (يعني يا عقل بلش ركّز واكتشف الملامح)
    train_loss, train_acc = 0, 0

    for x, y in train_loader:
        x, y = x.to(device), y.to(device)

        # الـ 5 خطوات السحرية: حزر، صفر العداد، احسب الغلط، ارجع لورا، وعدل قيم العصبونات
        output = model(x)
        optimizer.zero_grad()
        batch_loss = loss_function(output, y)
        batch_loss.backward()
        optimizer.step()

        train_loss += batch_loss.item()
        train_acc += get_batch_accuracy(output, y, train_N)

    print(f"Epoch [{epoch+1}/{epochs}] -> Training Accuracy: {train_acc*100:.2f}%")

print("--- Training finished successfully! ---\n")

# هنا بنجرب نفحص صورتك الخاصة اللي رفعتيها على كولاب
image_name = "my_digit.png"

if os.path.exists(image_name):
    print(f"Found '{image_name}', analyzing and predicting...")

    # بنفتح الصورة وبنحولها لأبيض وأسود، وبنصغر مقاسها لـ 28x28 بكسل بالملي
    raw_image = Image.open(image_name).convert('L')
    resize_transform = transforms.Compose([
        transforms.Resize((28, 28)),
        transforms.ToTensor()
    ])
    my_tensor = resize_transform(raw_image)

    # 💡 إذا كانت خلفية صورتك بيضاء والكتابة سوداء، شيل الـ # من السطر اللي تحت عشان يقلب الألوان وتطابق التدريب
    #my_tensor = 1.0 - my_tensor

    # بنضبط أبعاد المصفوفة وبنبعثها لكرت الشاشة
    my_tensor = my_tensor.to(device).unsqueeze(0)

    # بنحكي للعقل الاصطناعي: "أنت بقاعة الامتحان الآن، احزر شو هالرقم بدون ما تغير عصبوناتك"
    model.eval()
    with torch.no_grad():
        prediction = model(my_tensor)
        predicted_digit = prediction.argmax(dim=1).item()

    # بنعرض صورتك الأصلية وفوقها التخمين بالإنجليزية عشان ما يقلب الخط العربي في الرسمة
    plt.imshow(raw_image, cmap='gray')
    plt.title(f"AI Prediction: {predicted_digit}", fontsize=14)
    plt.axis('off')
    plt.show()
else:
    print(f"Notice: To test your own handwriting, upload an image named '{image_name}' to Colab and run the code again!")